name: Deploy

on:
  push:
    branches:
      - release
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache astro images
        uses: actions/cache@v3
        with:
          path: node_modules/.astro/image
          key: ${{ runner.os }}-astro-images
      - name: Cache Eslint
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: ${{ runner.os }}-node-${{ hasFiles('**/pnpm-lock.yaml', '**/.eslintrc.cjs') }}
      - name: Cache Prettier
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/prettier
          key: ${{ runner.os }}-node-${{ hasFiles('**/pnpm-lock.yaml', '**/.prettierrc.cjs')}}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: pnpm run fmt:check
      - name: Lint
        run: pnpm run lint
      - name: Check astro
        run: pnpm run check
      - name: Build
        run: pnpm run build
      - name: Deploy on Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish dist/ --project-name=website
