name: Deploy

on:
  push:
    branches:
      - release
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run fmt:check
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run build
      - if: github.ref == 'refs/heads/release'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish dist/ --project-name=website
